# 数据操作

## N维数组
N维数组是机器学习和神经网络的主要数据结构  

<img src="img/N维数组样例1.png" align="left" width="600">
<img src="img/N维数组样例2.png" align="left" width="600">

## 访问元素
<img src="img/访问元素.png" align="left" width="600">

## 数据操作实现

In [1]:
import torch

D:\Anaconda3\envs\projects\lib\site-packages\tqdm\auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


### 创建张量

张量表示一个数值组成的数组，这个数组可能有多个维度

In [2]:
x = torch.arange(12)
x

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

可以通过张量的`shape`属性来访问张量的形状和张量中元素的总数

In [3]:
x.shape

torch.Size([12])

In [4]:
x.numel()

12

`reshape`函数可以改变一个张量的形状而不改变元素数量和元素值

In [5]:
x = x.reshape(3,4)
x

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

使用全0、全1、其他常量或者从特定分布中随机采样的数字

In [6]:
torch.zeros((2,3,4))

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [7]:
torch.ones((2,3,4))

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

通过python列表（或嵌套列表）创建张量

In [8]:
torch.tensor([[2,1,4,3],[1,2,3,4],[4,3,2,1]])

tensor([[2, 1, 4, 3],
        [1, 2, 3, 4],
        [4, 3, 2, 1]])

### 张量运算

常见的标准算数运算符（`+`,`-`,`*`,`/`和`**`）都可以被升级为按元素运算

In [10]:
x = torch.tensor([1.0,2,4,8])
y = torch.tensor([2,2,2,2])
x + y, x - y, x * y, x / y, x ** y

(tensor([ 3.,  4.,  6., 10.]),
 tensor([-1.,  0.,  2.,  6.]),
 tensor([ 2.,  4.,  8., 16.]),
 tensor([0.5000, 1.0000, 2.0000, 4.0000]),
 tensor([ 1.,  4., 16., 64.]))

把多个张量连结在一起

In [11]:
x = torch.arange(12,dtype=torch.float32).reshape((3,4))
y = torch.tensor([[2.0,1,4,3],[1,2,3,4],[4,3,2,1]])
torch.cat((x,y),dim=0),torch.cat((x,y),dim=1)

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [ 2.,  1.,  4.,  3.],
         [ 1.,  2.,  3.,  4.],
         [ 4.,  3.,  2.,  1.]]),
 tensor([[ 0.,  1.,  2.,  3.,  2.,  1.,  4.,  3.],
         [ 4.,  5.,  6.,  7.,  1.,  2.,  3.,  4.],
         [ 8.,  9., 10., 11.,  4.,  3.,  2.,  1.]]))

通过逻辑运算符构建二元张量

In [12]:
x == y

tensor([[False,  True, False,  True],
        [False, False, False, False],
        [False, False, False, False]])

对张量中的所有元素求和会产生一个只有一个元素的张量

In [13]:
x.sum()

tensor(66.)

### 广播机制

即使形状不同，我们仍然可以通过调用**广播机制**来执行按元素操作（张量的维度需要一致）

In [14]:
a = torch.arange(3).reshape((3,1))
b = torch.arange(2).reshape((1,2))
a,b

(tensor([[0],
         [1],
         [2]]),
 tensor([[0, 1]]))

In [15]:
# 相当于把a和b都复制成3*2的矩阵
a + b

tensor([[0, 1],
        [1, 2],
        [2, 3]])

### 索引操作

可以用`[-1]`选择最后一个元素，用`[1:3]`选择第二个和第三个元素

In [18]:
x

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

In [16]:
x[-1]

tensor([ 8.,  9., 10., 11.])

In [17]:
x[1:3]

tensor([[ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

除读取外，我们还可以通过指定索引来将元素写入矩阵

In [19]:
x[1,2] = 9
x

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  9.,  7.],
        [ 8.,  9., 10., 11.]])

为多个元素赋值相同的值，我们只需要索引所有元素，然后为它们赋值

In [20]:
x[0:2,:] = 12
x

tensor([[12., 12., 12., 12.],
        [12., 12., 12., 12.],
        [ 8.,  9., 10., 11.]])

### 节省内存

运行一些操作可能会导致为新结果分配内存

In [21]:
before = id(y)
y = y + x
id(y) == before

False

执行原地操作

In [22]:
z = torch.zeros_like(y)
print(f'id(z):{id(z)}')
z[:] = x + y
print(f'id(z):{id(z)}')

id(z):2370418295088
id(z):2370418295088


In [23]:
z

tensor([[26., 25., 28., 27.],
        [25., 26., 27., 28.],
        [20., 21., 22., 23.]])

如果在后续计算中没有重复使用x，我们也可以使用`x[:]=x+y`或`x += y `来减少操作的内存开销

In [24]:
before = id(x)
x += y
id(x) == before

True

### 类型转换

转换为numpy张量

In [25]:
A = x.numpy()
B = torch.tensor(A)
type(A),type(B)

(numpy.ndarray, torch.Tensor)

将大小为1的张量转换为python标量

In [26]:
a = torch.tensor([3.5])
a, a.item(), float(a), int(a)

(tensor([3.5000]), 3.5, 3.5, 3)

# 数据预处理

## 创建数据集

创建一个人工数据集，并存储在csv文件

In [27]:
import os

os.makedirs(os.path.join('..','data'),exist_ok=True)
data_file = os.path.join('..','data','house_tiny.csv')
with open(data_file,'w') as f:
    f.write('NumRooms,Alley,Price\n')    # 列名
    f.write('NA,Pave,127500\n')    # 每行表示一个数据样本
    f.write('2,NA,106000\n')
    f.write('4,NA,178100\n')
    f.write('NA,NA,140000\n')

In [28]:
import pandas as pd

data = pd.read_csv(data_file)
print(data)

   NumRooms Alley   Price
0       NaN  Pave  127500
1       2.0   NaN  106000
2       4.0   NaN  178100
3       NaN   NaN  140000


## 处理缺失值

为了处理缺失的数据，典型的方法包括**插值**和**删除**，这里我们将考虑插值

In [29]:
inputs, outputs = data.iloc[:,0:2], data.iloc[:,2]
inputs = inputs.fillna(inputs.mean())
print(inputs)

   NumRooms Alley
0       3.0  Pave
1       2.0   NaN
2       4.0   NaN
3       3.0   NaN


C:\Users\gaoyu\AppData\Local\Temp\ipykernel_14272\926360299.py:2: FutureWarning: The default value of numeric_only in DataFrame.mean is deprecated. In a future version, it will default to False. In addition, specifying 'numeric_only=None' is deprecated. Select only valid columns or specify the value of numeric_only to silence this warning.
  inputs = inputs.fillna(inputs.mean())


对于`inputs`中的类别值或离散值，我们将'NaN'视为一个类别

In [30]:
inputs = pd.get_dummies(inputs,dummy_na=True)
print(inputs)

   NumRooms  Alley_Pave  Alley_nan
0       3.0           1          0
1       2.0           0          1
2       4.0           0          1
3       3.0           0          1


现在`inputs`和`outputs`中的所有条目都是数值类型，它们可以转换为张量格式

In [31]:
X, y = torch.tensor(inputs.values), torch.tensor(outputs.values)
X, y

(tensor([[3., 1., 0.],
         [2., 0., 1.],
         [4., 0., 1.],
         [3., 0., 1.]], dtype=torch.float64),
 tensor([127500, 106000, 178100, 140000]))

# 线性代数

<img src="img/线性代数1.png" align="left" width="600">

## 标量

<img src="img/标量.png" align="left" width="350">

In [32]:
x = torch.tensor([3.0])
y = torch.tensor([2.0])
x + y, x * y, x / y, x ** y

(tensor([5.]), tensor([6.]), tensor([1.5000]), tensor([9.]))

## 向量

<img src="img/向量.png" align="left" width="450">

<img src="img/向量2.png" align="left" width="450">

<img src="img/向量3.png" align="left" width="400">

In [33]:
x = torch.arange(4)
x

tensor([0, 1, 2, 3])

In [34]:
x[3]

tensor(3)

In [35]:
# 访问张量的长度
len(x)

4

In [36]:
# 只有一个轴的张量，形状只有一个元素
x.shape

torch.Size([4])

## 矩阵

<img src="img/矩阵1.png" align="left" width="400">

<img src="img/矩阵2.png" align="left" width="400">

<img src="img/矩阵3.png" align="left" width="450">

<img src="img/矩阵4.png" align="left" width="450">

### 特殊矩阵

<img src="img/特殊矩阵1.png" align="left" width="500">

<img src="img/特殊矩阵2.png" align="left" width="450">

<img src="img/特殊矩阵3.png" align="left" width="450">

<img src="img/特征向量和特征值.png" align="left" width="550">

In [37]:
A = torch.arange(20).reshape(5,4)
A

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15],
        [16, 17, 18, 19]])

In [38]:
# 矩阵转置
A.T

tensor([[ 0,  4,  8, 12, 16],
        [ 1,  5,  9, 13, 17],
        [ 2,  6, 10, 14, 18],
        [ 3,  7, 11, 15, 19]])

In [39]:
# 对称矩阵
B = torch.tensor([[1,2,3],[2,0,4],[3,4,5]])
B

tensor([[1, 2, 3],
        [2, 0, 4],
        [3, 4, 5]])

In [40]:
B == B.T

tensor([[True, True, True],
        [True, True, True],
        [True, True, True]])

In [41]:
X = torch.arange(24).reshape((2,3,4))
X

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])

给定具有相同形状的任何两个张量，任何按元素二元运算的结果都将是相同形状的张量

In [42]:
A = torch.arange(20,dtype=torch.float32).reshape(5,4)
B = A.clone()    
A ,A + B

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [12., 13., 14., 15.],
         [16., 17., 18., 19.]]),
 tensor([[ 0.,  2.,  4.,  6.],
         [ 8., 10., 12., 14.],
         [16., 18., 20., 22.],
         [24., 26., 28., 30.],
         [32., 34., 36., 38.]]))

两个矩阵的按元素乘法称为**哈达玛积**

In [43]:
A * B

tensor([[  0.,   1.,   4.,   9.],
        [ 16.,  25.,  36.,  49.],
        [ 64.,  81., 100., 121.],
        [144., 169., 196., 225.],
        [256., 289., 324., 361.]])

In [45]:
a = 2
X = torch.arange(24).reshape(2,3,4)
a,X,a + X, (a * X).shape

(2,
 tensor([[[ 0,  1,  2,  3],
          [ 4,  5,  6,  7],
          [ 8,  9, 10, 11]],
 
         [[12, 13, 14, 15],
          [16, 17, 18, 19],
          [20, 21, 22, 23]]]),
 tensor([[[ 2,  3,  4,  5],
          [ 6,  7,  8,  9],
          [10, 11, 12, 13]],
 
         [[14, 15, 16, 17],
          [18, 19, 20, 21],
          [22, 23, 24, 25]]]),
 torch.Size([2, 3, 4]))

In [63]:
# 计算任意形状张量的元素和
A = torch.arange(40,dtype=torch.float32).reshape(2,5,4)
A, A.shape, A.sum()

(tensor([[[ 0.,  1.,  2.,  3.],
          [ 4.,  5.,  6.,  7.],
          [ 8.,  9., 10., 11.],
          [12., 13., 14., 15.],
          [16., 17., 18., 19.]],
 
         [[20., 21., 22., 23.],
          [24., 25., 26., 27.],
          [28., 29., 30., 31.],
          [32., 33., 34., 35.],
          [36., 37., 38., 39.]]]),
 torch.Size([2, 5, 4]),
 tensor(780.))

In [47]:
# 指定求和汇总张量的轴
A_sum_axis_0 = A.sum(axis=0)
A_sum_axis_0, A_sum_axis_0.shape

(tensor([[20, 22, 24, 26],
         [28, 30, 32, 34],
         [36, 38, 40, 42],
         [44, 46, 48, 50],
         [52, 54, 56, 58]]),
 torch.Size([5, 4]))

In [48]:
A_sum_axis_1 = A.sum(axis=1)
A_sum_axis_1, A_sum_axis_1.shape

(tensor([[ 40,  45,  50,  55],
         [140, 145, 150, 155]]),
 torch.Size([2, 4]))

In [50]:
A.sum(axis=[0,1])

tensor([180, 190, 200, 210])

一个与求和相关的量是**平均值**

In [65]:
A.mean(), A.sum() / A.numel()

(tensor(19.5000), tensor(19.5000))

In [64]:
A.mean(axis=0), A.sum(axis=0) / A.shape[0]

(tensor([[10., 11., 12., 13.],
         [14., 15., 16., 17.],
         [18., 19., 20., 21.],
         [22., 23., 24., 25.],
         [26., 27., 28., 29.]]),
 tensor([[10., 11., 12., 13.],
         [14., 15., 16., 17.],
         [18., 19., 20., 21.],
         [22., 23., 24., 25.],
         [26., 27., 28., 29.]]))

计算总和或均值时保持轴数不变

In [66]:
sum_A = A.sum(axis=1,keepdims=True)
sum_A

tensor([[[ 40.,  45.,  50.,  55.]],

        [[140., 145., 150., 155.]]])

通过广播将A除以sum_A

In [67]:
A / sum_A

tensor([[[0.0000, 0.0222, 0.0400, 0.0545],
         [0.1000, 0.1111, 0.1200, 0.1273],
         [0.2000, 0.2000, 0.2000, 0.2000],
         [0.3000, 0.2889, 0.2800, 0.2727],
         [0.4000, 0.3778, 0.3600, 0.3455]],

        [[0.1429, 0.1448, 0.1467, 0.1484],
         [0.1714, 0.1724, 0.1733, 0.1742],
         [0.2000, 0.2000, 0.2000, 0.2000],
         [0.2286, 0.2276, 0.2267, 0.2258],
         [0.2571, 0.2552, 0.2533, 0.2516]]])

某个轴计算A元素的累计总和

In [68]:
A.cumsum(axis=0)

tensor([[[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [12., 13., 14., 15.],
         [16., 17., 18., 19.]],

        [[20., 22., 24., 26.],
         [28., 30., 32., 34.],
         [36., 38., 40., 42.],
         [44., 46., 48., 50.],
         [52., 54., 56., 58.]]])

点积是相同位置的按元素乘积的和

In [71]:
x = torch.arange(4,dtype=torch.float32)
y = torch.ones(4,dtype=torch.float32)
x, y, torch.dot(x,y)

(tensor([0., 1., 2., 3.]), tensor([1., 1., 1., 1.]), tensor(6.))

矩阵向量积Ax是一个长度为m的列向量

In [78]:
A = torch.arange(20,dtype=torch.float32).reshape(5,4)
A.shape, x.shape,torch.mv(A,x)

(torch.Size([5, 4]), torch.Size([4]), tensor([ 14.,  38.,  62.,  86., 110.]))

矩阵乘法AB可以看作是简单地执行m次矩阵-向量积，并将结果拼接在一起，形成一个n*m矩阵

In [79]:
B = torch.ones(4,3)
torch.mm(A,B)

tensor([[ 6.,  6.,  6.],
        [22., 22., 22.],
        [38., 38., 38.],
        [54., 54., 54.],
        [70., 70., 70.]])

L2范数是向量元素平方和的平方根

In [81]:
u = torch.tensor([3.0,-4.0])
torch.norm(u)

tensor(5.)

L1范数是向量元素的绝对值之和

In [82]:
torch.abs(u).sum()

tensor(7.)

矩阵的佛罗贝尼乌斯范数是矩阵元素的平方和的平方根

In [83]:
torch.norm(torch.ones((4,9)))

tensor(6.)

# 矩阵计算

## 导数

<img src="img/标量导数1.png" align="left" width="600">

<img src="img/标量导数2.png" align="left" width="500">

<img src="img/亚导数1.png" align="left" width="300">

<img src="img/亚导数2.png" align="left" width="300">

## 梯度

<img src="img/梯度1.png" align="left" width="300">

1. y是标量，x是列向量，导数是一个行向量  

<img src="img/梯度2.png" align="left" width="300">

<img src="img/梯度3.png" align="left" width="500">

2. y是列向量，x是标量，导数是一个列向量  

<img src="img/梯度4.png" align="left" width="300">

3. y是列向量，x是列向量，导数是一个矩阵  

<img src="img/梯度5.png" align="left" width="300">

# 自动求导

<img src="img/自动求导1.png" align="left" width="400">

## 计算图

<img src="img/计算图.png" align="left" width="350">

## 自动求导的两种模式

<img src="img/自动求导2.png" align="left" width="400">

<img src="img/反向累积.png" align="left" width="300">

In [90]:
x = torch.arange(4.0)
x

tensor([0., 1., 2., 3.])

In [91]:
# 存储梯度
x.requires_grad_(True)
x.grad 

In [92]:
y = 2*torch.dot(x,x)
y

tensor(28., grad_fn=<MulBackward0>)

In [93]:
# 通过反向传播函数来自动计算y关于x每个分量的梯度
y.backward()
x.grad

tensor([ 0.,  4.,  8., 12.])

In [94]:
x.grad == 4*x

tensor([True, True, True, True])

In [96]:
# 在默认情况下，pytorch会累积梯度，我们需要清除之前的值
x.grad.zero_()
y = x.sum()
y.backward()
x.grad

tensor([1., 1., 1., 1.])

在深度学习中，我们的目的不是计算微分矩阵，而是批量中每个样本单独计算的偏导数之和

In [97]:
x.grad.zero_()
y = x*x
y.sum().backward()
x.grad

tensor([0., 2., 4., 6.])

将某些计算移动到记录的计算图之外

In [98]:
x.grad.zero_()
y = x*x
u = y.detach()
z = u*x

z.sum().backward()
x.grad == u

tensor([True, True, True, True])

In [99]:
x.grad.zero_()
y.sum().backward()
x.grad == 2*x

tensor([True, True, True, True])

此外，即使构建函数的计算图需要通过python控制流（例如，条件、循环或任意函数调用），我们仍然可以计算得到的变量的梯度

In [101]:
def f(a):
    b = a*2
    while b.norm()<1000:
        b=b*2
    if b.sum()>0:
        c=b
    else:
        c=100*b
    return c

a = torch.randn(size=(),requires_grad=True)
d = f(a)
d.backward()

a.grad == d/a

tensor(True)